export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIDE_MENU_OPEN = 'SIDE_MENU_OPEN';
export const SIDE_MENU_CLOSE = 'SIDE_MENU_CLOSE';

export const LOGIN_FROM_OPEN = 'LOGIN_FROM_OPEN';

export const LIST_RACK_LOCATION_REQUEST = 'LIST_RACK_LOCATION_REQUEST';
export const LIST_RACK_LOCATION_SUCCESS = 'LIST_RACK_LOCATION_SUCCESS';
export const LIST_RACK_LOCATION_FAILURE = 'LIST_RACK_LOCATION_FAILURE';

export const LIST_RACK_DETAIL_REQUEST = 'LIST_RACK_DETAIL_REQUEST';
export const LIST_RACK_DETAIL_SUCCESS = 'LIST_RACK_DETAIL_SUCCESS';
export const LIST_RACK_DETAIL_FAILURE = 'LIST_RACK_DETAIL_FAILURE';

export const SHOW_RACK_LOCATION_REQUEST = 'SHOW_RACK_LOCATION_REQUEST';
export const SHOW_RACK_LOCATION_SUCCESS = 'SHOW_RACK_LOCATION_SUCCESS';
export const SHOW_RACK_LOCATION_FAILURE = 'SHOW_RACK_LOCATION_FAILURE';

export const HIGHLIGHT_LOCATIONS = 'HIGHLIGHT_LOCATIONS';

export const LISTENING_CHANGED_OPTIONS = 'LISTENING_CHANGED_OPTIONS';

export const BYDATE_TMP_PASSVALUE = 'BYDATE_TMP_PASSVALUE';

export const LIST_ALLITEMS_SELECT_REQUEST = 'LIST_ALLITEMS_SELECT_REQUEST';
export const LIST_ALLITEMS_SELECT_SUCCESS = 'LIST_ALLITEMS_SELECT_SUCCESS';
export const LIST_ALLITEMS_SELECT_FAILURE = 'LIST_ALLITEMS_SELECT_FAILURE';

export const LIST_WMS_STATUS_REQUEST = 'LIST_WMS_STATUS_REQUEST';
export const LIST_WMS_STATUS_SUCCESS = 'LIST_WMS_STATUS_SUCCESS';
export const LIST_WMS_STATUS_FAILURE = 'LIST_WMS_STATUS_FAILURE';

export const DOWNLOAD_INVENTORY_REPORT_REQUEST = 'DOWNLOAD_INVENTORY_REPORT_REQUEST';
export const DOWNLOAD_INVENTORY_REPORT_SUCCESS = 'DOWNLOAD_INVENTORY_REPORT_SUCCESS';
export const DOWNLOAD_INVENTORY_REPORT_FAILURE = 'DOWNLOAD_INVENTORY_REPORT_FAILURE';
